<?php
/*
 *  Created by Sheepla. http://sheepla.com
 *  
 */

if (Mage::getConfig()->getModuleConfig('Orba_Sheepla')->is('active', 'true')):
    ?>
    
    <div id="sheepla-notification"></div>

    <link rel="stylesheet" type="text/css" href="<?php echo Mage::getStoreConfig('sheepla/api_config/api_widget_css'); ?>">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('sheepla'); ?>/custom_admin.css">
    <!--Importujemy bibliotekę JavaScript-->
    <script type="text/javascript" src="<?php echo Mage::getStoreConfig('sheepla/api_config/api_widget_js'); ?>"></script>

    <!--Otwieramy blok kodu typu javascript-->
    <script type="text/javascript">
        //tworzymy obiekt konfiguracji dla obienktu sheepla
        sheepla.config = {
            apikey: '<?php echo Mage::getStoreConfig( 'sheepla/api_config/api_key' ) ?>',
            cultureId: '<?php echo Mage::helper('sheepla/data')->getCultureIdByLocaleCode(Mage::app()->getLocale()->getLocaleCode()); ?>'
        };
        //inicjalizujemy obiekt sheepla
        sheepla.init();
        sheepla.get_notifications('#sheepla-notification');

    </script>

<?php endif; ?>