<?php if ($_shippingRateGroups = $this->getShippingRates()): ?>
    <div id="order-shipping-method-choose" style="display:none">
        <dl class="shipment-methods">

            <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
                <dt><strong><?php echo $this->getCarrierName($code) ?></strong></dt>
                <dd>
                    <ul>
                        <?php foreach ($_rates as $_rate): ?>
                            <?php $_radioProperty = 'name="order[shipping_method]" type="radio" onclick="order.setShippingMethod(this.value)"' ?>
                            <?php $_code = $_rate->getCode() ?>
                            <li>
                                <?php if ($_rate->getErrorMessage()): ?>
                                    <ul class="messages">
                                        <li class="error-msg"><?php echo $_rate->getErrorMessage() ?></li>
                                    </ul>
                                <?php else: ?>
                                    <?php $_checked = $this->isMethodActive($_code) ? 'checked="checked"' : '' ?>
                                    <input <?php echo $_radioProperty ?> value="<?php echo $_code ?>" id="s_method_<?php echo $_code ?>" <?php echo $_checked ?>/>
                                    <label class="normal" for="s_method_<?php echo $_code ?>">
                                        <?php echo $_rate->getMethodTitle() ? $_rate->getMethodTitle() : $_rate->getMethodDescription() ?> -
                                        <strong>
                                            <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                            <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>

                                            <?php echo $_excl; ?>
                                            <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                                (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                            <?php endif; ?>
                                        </strong>
                                    </label>
                                <?php endif ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </dd>
            <?php endforeach; ?>
        </dl>
    </div>
    <?php if ($_rate = $this->getActiveMethodRate()): ?>

        <div id="order-shipping-method-info">
            <strong><?php echo $this->getCarrierName($_rate->getCarrier()) ?></strong><br/>
            <?php echo $_rate->getMethodTitle() ? $_rate->getMethodTitle() : $_rate->getMethodDescription() ?> -
            <strong>
                <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>

                <?php echo $_excl; ?>
                <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                    (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                <?php endif; ?>
            </strong>
            <!--input type="text" class="input-text" style="width:70px"/-->
            <br/>
            <?php 
            
            if ($_rate->getCarrier() == 'sheepla') {
                
                
            
                // check is PickPoint exist
                // paczkomat
                // $chosenPickpoint = 'false';
                // if (Mage::helper('core')->isModuleEnabled('Orba_Allegro')) {
                // $transactionId = $this->getQuote()->getOrbaallegroTransactionId();
                // $pickPointData = Mage::getModel('orbaallegro/transaction')->load($transactionId)->getAddress(Orba_Allegro_Model_Transaction_Address::TYPE_PICKPOINT);
                // if ($pickPointData) {
                // $chosenPickpoint = preg_replace('/Paczkomat /', '' , $pickPointData->getFullname());
                // }
                // }


                // 0.9.11 dpanek 16.06.2014
                // pobieram dane z widgetu

                $sessionData = Mage::getModel( 'adminhtml/session_quote' );
                $storeId = $sessionData->getData( 'store_id' );
                        
                $shConf = Mage::getStoreConfig('sheepla/' . $_rate->getMethod() , $storeId );
                
                if (!empty($shConf['template_id'])) {
                    
                    $oldSheeplaData = $sessionData->getData( 'old_sheepla_data' );
                    
                    if( isset( $oldSheeplaData[ 'order_id' ] ) ) {

                        $specials = Mage::helper( 'sheepla/data' )->getSpecialData( $oldSheeplaData[ 'order_id' ] );
                    }
            
            ?>
                    
                    <div class="sheepla-sdk-area">&nbsp;</div>
                
                    <?php $city = $this->getAddress()->getCity(); ?>
                    <script type="text/javascript">
                        //<![CDATA[
                        if (sheepla.query('#email').val().length > 0) {
                            var email = sheepla.query('#email').val();
                        }
                        
                        sheepla_onclick('<?php echo $shConf['template_id']; ?>', '.sheepla-sdk-area', '<?php echo $city; ?>','<?php echo $_rate->getCode(); ?>','<?php echo $specials; ?>');
                        //]]>
                    </script>
                    
                <?php } ?>
            <?php } ?>
            <a href="#" onclick="$('order-shipping-method-info').hide();$('order-shipping-method-choose').show();return false">
                <?php echo Mage::helper('sales')->__('Click to change shipping method') ?>
            </a>
        </div>
    <?php else: ?>
        <script type="text/javascript">$('order-shipping-method-choose').show();</script>
    <?php endif; ?>
<?php elseif ($this->getIsRateRequest()): ?>
    <strong><?php echo Mage::helper('sales')->__('Sorry, no quotes are available for this order at this time.') ?></strong>
<?php else: ?>
    <div id="order-shipping-method-summary">
        <a href="#" onclick="order.loadShippingRates();return false">
            <?php echo Mage::helper('sales')->__('Get shipping methods and rates') ?>
        </a>
        <input type="hidden" name="order[has_shipping]" value="" class="required-entry">
    </div>
<?php endif; ?>
<div style="display:none;" id="shipping-method-overlay" class="overlay"><span><?php echo $this->__('Shipping method selection is not applicable') ?></span></div>
<script type="text/javascript">
    order.overlay('shipping-method-overlay', <?php if ($this->getQuote()->isVirtual()): ?>false<?php else: ?>true<?php endif; ?>);
    order.overlay('address-shipping-overlay', <?php if ($this->getQuote()->isVirtual()): ?>false<?php else: ?>true<?php endif; ?>);
</script>